import type { SupabaseClient } from "@supabase/supabase-js";

import type { HsppAssemblyRecoveryWorkItem } from "@/lib/hspp/readHsppAssemblyRecoveryWorkItems";

import {
  claimHsppAssemblyAssessmentRetryIdentity,
  type ClaimedHsppAssemblyAssessmentRetryIdentity,
} from "@/lib/hspp/claimHsppAssemblyAssessmentRetryIdentity";

import {
  readHsppAssemblyAssessmentCompletion,
  type HsppAssemblyAssessmentCompletion,
} from "@/lib/hspp/readHsppAssemblyAssessmentCompletion";

import {
  acquireHsppAssemblyAssessmentExecutionLease,
  releaseHsppAssemblyAssessmentExecutionLease,
  type HsppAssemblyAssessmentExecutionLeaseAcquire,
} from "@/lib/hspp/hsppAssemblyAssessmentExecutionLease";

import type { HsppAssessmentExecutionLeaseContext } from "@/lib/hspp/hsppAssessmentExecutionLeaseContext";

import {
  recordHsppAssemblyAssessmentCompletionUnderExecutionLease,
  type RecordedHsppAssemblyAssessmentCompletionUnderExecutionLease,
} from "@/lib/hspp/recordHsppAssemblyAssessmentCompletionUnderExecutionLease";

import {
  runHsppSealedEvidenceAssemblyCorroboratedOperationalAssessmentPersistenceRouting,
  type RunHsppSealedEvidenceAssemblyCorroboratedOperationalAssessmentPersistenceRoutingResult,
} from "@/lib/hspp/runHsppSealedEvidenceAssemblyCorroboratedOperationalAssessmentPersistenceRouting";

export const HSPP_SEALED_ASSEMBLY_RECOVERY_ASSESSMENT_RUNNER_VERSION =
  "hspp-sealed-assembly-recovery-assessment-runner-v2" as const;

export type RunHsppSealedAssemblyRecoveryAssessmentInput = {
  supabase: SupabaseClient;

  /**
   * One already-discovered Q13b persisted recovery work item.
   *
   * This runner does not perform recovery discovery itself.
   */
  workItem: HsppAssemblyRecoveryWorkItem;

  /**
   * Caller-owned proposal for first-time retry identity creation.
   *
   * Q13d2 remains the canonical first-writer-wins boundary. If the assembly
   * already has a retry identity, Q13d2 returns its existing assessedAt.
   *
   * This value is not generated by this runner.
   */
  proposedAssessedAt: string;

  /**
   * Caller-owned execution lease identity.
   *
   * Q13d7 never generates or replaces this token.
   */
  leaseToken: string;

  /**
   * Caller-owned execution lease duration in seconds.
   *
   * The execution-lease primitive remains the sole validator.
   */
  leaseSeconds: number;
};

type HsppSealedAssemblyRecoveryAssessmentCommonResult = {
  runnerVersion: typeof HSPP_SEALED_ASSEMBLY_RECOVERY_ASSESSMENT_RUNNER_VERSION;
};

export type HsppSealedAssemblyRecoveryAssessmentAlreadyCompletedResult =
  HsppSealedAssemblyRecoveryAssessmentCommonResult & {
    branch: "ALREADY_COMPLETED";

    completion: HsppAssemblyAssessmentCompletion;

    retryIdentity: null;

    terminalResult: null;
  };

export type HsppSealedAssemblyRecoveryAssessmentExecutionBusyResult =
  HsppSealedAssemblyRecoveryAssessmentCommonResult & {
    branch: "EXECUTION_BUSY";

    leaseAcquisition: Extract<
      HsppAssemblyAssessmentExecutionLeaseAcquire,
      { state: "BUSY" | "CONTENDED" }
    >;

    completion: null;

    retryIdentity: null;

    terminalResult: null;
  };

export type HsppSealedAssemblyRecoveryAssessmentCompletedResult =
  HsppSealedAssemblyRecoveryAssessmentCommonResult & {
    branch: "ASSESSMENT_COMPLETED";

    completion: RecordedHsppAssemblyAssessmentCompletionUnderExecutionLease;

    retryIdentity: ClaimedHsppAssemblyAssessmentRetryIdentity;

    terminalResult: RunHsppSealedEvidenceAssemblyCorroboratedOperationalAssessmentPersistenceRoutingResult;
  };

export type RunHsppSealedAssemblyRecoveryAssessmentResult =
  | HsppSealedAssemblyRecoveryAssessmentAlreadyCompletedResult
  | HsppSealedAssemblyRecoveryAssessmentExecutionBusyResult
  | HsppSealedAssemblyRecoveryAssessmentCompletedResult;

function requireNonBlank(value: unknown, fieldName: string): string {
  if (typeof value !== "string") {
    throw new Error(`${fieldName} is required.`);
  }

  const normalized = value.trim();

  if (!normalized) {
    throw new Error(`${fieldName} is required.`);
  }

  return normalized;
}

/**
 * B7490-07Q13d7 SEALED recovery continuation with recovery-only execution
 * ownership.
 *
 * Sequence:
 *
 * 1. completion preflight;
 * 2. acquire the caller-owned execution lease;
 * 3. if BUSY, stop without retry identity or Q12 work;
 * 4. re-read completion while ownership is held;
 * 5. claim/recover the canonical retry identity;
 * 6. execute Q12 with the exact execution-lease context;
 * 7. record immutable completion through the fenced completion writer;
 * 8. release ownership on every acquired-lease exit path.
 *
 * This runner does not generate assessment time, lease tokens, lease duration,
 * discovery work, OPEN sealing, trust-change behavior or public execution
 * wiring. Lease renewal remains outside this focused milestone.
 */
export async function runHsppSealedAssemblyRecoveryAssessment({
  supabase,
  workItem,
  proposedAssessedAt,
  leaseToken,
  leaseSeconds,
}: RunHsppSealedAssemblyRecoveryAssessmentInput): Promise<RunHsppSealedAssemblyRecoveryAssessmentResult> {
  if (!workItem || typeof workItem !== "object") {
    throw new Error(
      "B7490-07Q13d7 requires one persisted Q13b recovery work item.",
    );
  }

  const organizationId = requireNonBlank(
    workItem.organizationId,
    "workItem.organizationId",
  );

  const assemblyId = requireNonBlank(
    workItem.assemblyId,
    "workItem.assemblyId",
  );

  if (workItem.assemblyState !== "SEALED") {
    throw new Error(
      "B7490-07Q13d7 may continue only a persisted SEALED assembly recovery work item.",
    );
  }

  const existingCompletion = await readHsppAssemblyAssessmentCompletion({
    supabase,
    organizationId,
    assemblyId,
  });

  if (existingCompletion !== null) {
    return {
      runnerVersion: HSPP_SEALED_ASSEMBLY_RECOVERY_ASSESSMENT_RUNNER_VERSION,

      branch: "ALREADY_COMPLETED",

      completion: existingCompletion,

      retryIdentity: null,

      terminalResult: null,
    };
  }

  const leaseAcquisition =
    await acquireHsppAssemblyAssessmentExecutionLease({
      supabase,
      organizationId,
      assemblyId,
      leaseToken,
      leaseSeconds,
    });

  if (
    leaseAcquisition.state === "BUSY" ||
    leaseAcquisition.state === "CONTENDED"
  ) {
    return {
      runnerVersion: HSPP_SEALED_ASSEMBLY_RECOVERY_ASSESSMENT_RUNNER_VERSION,

      branch: "EXECUTION_BUSY",

      leaseAcquisition,

      completion: null,

      retryIdentity: null,

      terminalResult: null,
    };
  }

  const executionLease: HsppAssessmentExecutionLeaseContext = {
    assemblyId: leaseAcquisition.assemblyId,
    leaseToken: leaseAcquisition.leaseToken,
  };

  let primaryError: unknown = null;

  try {
    const completionAfterAcquire =
      await readHsppAssemblyAssessmentCompletion({
        supabase,
        organizationId,
        assemblyId,
      });

    if (completionAfterAcquire !== null) {
      return {
        runnerVersion:
          HSPP_SEALED_ASSEMBLY_RECOVERY_ASSESSMENT_RUNNER_VERSION,

        branch: "ALREADY_COMPLETED",

        completion: completionAfterAcquire,

        retryIdentity: null,

        terminalResult: null,
      };
    }

    const retryIdentity = await claimHsppAssemblyAssessmentRetryIdentity({
      supabase,
      organizationId,
      assemblyId,
      proposedAssessedAt,
    });

    const terminalResult =
      await runHsppSealedEvidenceAssemblyCorroboratedOperationalAssessmentPersistenceRouting(
        {
          supabase,

          organizationId: retryIdentity.organizationId,

          assemblyId: retryIdentity.assemblyId,

          assessedAt: retryIdentity.assessedAt,

          executionLease,
        },
      );

    const completion =
      await recordHsppAssemblyAssessmentCompletionUnderExecutionLease({
        supabase,

        organizationId: retryIdentity.organizationId,

        assemblyId: retryIdentity.assemblyId,

        leaseToken: executionLease.leaseToken,

        terminalResult,
      });

    return {
      runnerVersion: HSPP_SEALED_ASSEMBLY_RECOVERY_ASSESSMENT_RUNNER_VERSION,

      branch: "ASSESSMENT_COMPLETED",

      completion,

      retryIdentity,

      terminalResult,
    };
  } catch (error) {
    primaryError = error;

    throw error;
  } finally {
    try {
      const release =
        await releaseHsppAssemblyAssessmentExecutionLease({
          supabase,

          organizationId: leaseAcquisition.organizationId,

          assemblyId: leaseAcquisition.assemblyId,

          leaseToken: leaseAcquisition.leaseToken,
        });

      if (release.state === "CONTENDED") {
        throw new Error(
          "HSPP sealed assembly recovery lease release was contended.",
        );
      }
    } catch (releaseError) {
      if (primaryError === null) {
        throw releaseError;
      }
    }
  }
}
