import type { SupabaseClient } from "@supabase/supabase-js";

import type { HsppAssemblyRecoveryWorkItem } from "@/lib/hspp/readHsppAssemblyRecoveryWorkItems";

import {
  claimHsppAssemblyAssessmentRetryIdentity,
  type ClaimedHsppAssemblyAssessmentRetryIdentity,
} from "@/lib/hspp/claimHsppAssemblyAssessmentRetryIdentity";

import {
  readHsppAssemblyAssessmentCompletion,
  type HsppAssemblyAssessmentCompletion,
} from "@/lib/hspp/readHsppAssemblyAssessmentCompletion";

import {
  recordHsppAssemblyAssessmentCompletion,
  type RecordedHsppAssemblyAssessmentCompletion,
} from "@/lib/hspp/recordHsppAssemblyAssessmentCompletion";

import {
  runHsppSealedEvidenceAssemblyCorroboratedOperationalAssessmentPersistenceRouting,
  type RunHsppSealedEvidenceAssemblyCorroboratedOperationalAssessmentPersistenceRoutingResult,
} from "@/lib/hspp/runHsppSealedEvidenceAssemblyCorroboratedOperationalAssessmentPersistenceRouting";

export const HSPP_SEALED_ASSEMBLY_RECOVERY_ASSESSMENT_RUNNER_VERSION =
  "hspp-sealed-assembly-recovery-assessment-runner-v1" as const;

export type RunHsppSealedAssemblyRecoveryAssessmentInput = {
  supabase: SupabaseClient;

  /**
   * One already-discovered Q13b persisted recovery work item.
   *
   * This runner does not perform recovery discovery itself.
   */
  workItem: HsppAssemblyRecoveryWorkItem;

  /**
   * Caller-owned proposal for first-time retry identity creation.
   *
   * Q13d2 remains the canonical first-writer-wins boundary. If the assembly
   * already has a retry identity, Q13d2 returns its existing assessedAt.
   *
   * This value is not generated by this runner.
   */
  proposedAssessedAt: string;
};

type HsppSealedAssemblyRecoveryAssessmentCommonResult = {
  runnerVersion: typeof HSPP_SEALED_ASSEMBLY_RECOVERY_ASSESSMENT_RUNNER_VERSION;
};

export type HsppSealedAssemblyRecoveryAssessmentAlreadyCompletedResult =
  HsppSealedAssemblyRecoveryAssessmentCommonResult & {
    branch: "ALREADY_COMPLETED";

    completion: HsppAssemblyAssessmentCompletion;

    retryIdentity: null;

    terminalResult: null;
  };

export type HsppSealedAssemblyRecoveryAssessmentCompletedResult =
  HsppSealedAssemblyRecoveryAssessmentCommonResult & {
    branch: "ASSESSMENT_COMPLETED";

    completion: RecordedHsppAssemblyAssessmentCompletion;

    retryIdentity: ClaimedHsppAssemblyAssessmentRetryIdentity;

    terminalResult: RunHsppSealedEvidenceAssemblyCorroboratedOperationalAssessmentPersistenceRoutingResult;
  };

export type RunHsppSealedAssemblyRecoveryAssessmentResult =
  | HsppSealedAssemblyRecoveryAssessmentAlreadyCompletedResult
  | HsppSealedAssemblyRecoveryAssessmentCompletedResult;

function requireNonBlank(value: unknown, fieldName: string): string {
  if (typeof value !== "string") {
    throw new Error(`${fieldName} is required.`);
  }

  const normalized = value.trim();

  if (!normalized) {
    throw new Error(`${fieldName} is required.`);
  }

  return normalized;
}

/**
 * B7490-07Q13d7 single-work-item SEALED recovery assessment continuation.
 *
 * The caller supplies one already-discovered Q13b work item.
 *
 * Persisted completion is checked before retry identity or assessment work.
 * If completion already exists, recovery stops immediately.
 *
 * Otherwise Q13d2 claims or recovers the canonical retry identity. Q12 then
 * receives that exact canonical assessedAt. The exact terminal Q12 result is
 * passed to Q13d5, which records or recovers immutable completion.
 *
 * This runner performs no discovery, OPEN sealing, direct table/RPC access,
 * evidence/member mutation, public execution wiring or time generation.
 */
export async function runHsppSealedAssemblyRecoveryAssessment({
  supabase,
  workItem,
  proposedAssessedAt,
}: RunHsppSealedAssemblyRecoveryAssessmentInput): Promise<RunHsppSealedAssemblyRecoveryAssessmentResult> {
  if (!workItem || typeof workItem !== "object") {
    throw new Error(
      "B7490-07Q13d7 requires one persisted Q13b recovery work item.",
    );
  }

  const organizationId = requireNonBlank(
    workItem.organizationId,
    "workItem.organizationId",
  );

  const assemblyId = requireNonBlank(
    workItem.assemblyId,
    "workItem.assemblyId",
  );

  if (workItem.assemblyState !== "SEALED") {
    throw new Error(
      "B7490-07Q13d7 may continue only a persisted SEALED assembly recovery work item.",
    );
  }

  const existingCompletion = await readHsppAssemblyAssessmentCompletion({
    supabase,
    organizationId,
    assemblyId,
  });

  if (existingCompletion !== null) {
    return {
      runnerVersion: HSPP_SEALED_ASSEMBLY_RECOVERY_ASSESSMENT_RUNNER_VERSION,

      branch: "ALREADY_COMPLETED",

      completion: existingCompletion,

      retryIdentity: null,

      terminalResult: null,
    };
  }

  const retryIdentity = await claimHsppAssemblyAssessmentRetryIdentity({
    supabase,
    organizationId,
    assemblyId,
    proposedAssessedAt,
  });

  const terminalResult =
    await runHsppSealedEvidenceAssemblyCorroboratedOperationalAssessmentPersistenceRouting(
      {
        supabase,

        organizationId: retryIdentity.organizationId,

        assemblyId: retryIdentity.assemblyId,

        assessedAt: retryIdentity.assessedAt,
      },
    );

  const completion = await recordHsppAssemblyAssessmentCompletion({
    supabase,

    organizationId: retryIdentity.organizationId,

    assemblyId: retryIdentity.assemblyId,

    terminalResult,
  });

  return {
    runnerVersion: HSPP_SEALED_ASSEMBLY_RECOVERY_ASSESSMENT_RUNNER_VERSION,

    branch: "ASSESSMENT_COMPLETED",

    completion,

    retryIdentity,

    terminalResult,
  };
}
