import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

const wrapperPath =
  "lib/route-safety/providers/persistRouteSafetyProviderSnapshotRetrieval.ts";

const source =
  fs.readFileSync(
    wrapperPath,
    "utf8"
  );

test(
  "defines one provider-neutral atomic snapshot persistence wrapper",
  () => {
    assert.match(
      source,
      /export async function persistRouteSafetyProviderSnapshotRetrieval/
    );

    assert.match(
      source,
      /persist_route_safety_provider_snapshot_retrieval/
    );

    assert.equal(
      (
        source.match(
          /\.rpc\s*\(/g
        ) ?? []
      ).length,
      1
    );
  }
);

test(
  "maps the complete camelCase wrapper input to the exact RPC argument names",
  () => {
    const mappings = [
      [
        "p_organization_id",
        "organizationId",
      ],
      [
        "p_provider",
        "provider",
      ],
      [
        "p_source_stream",
        "sourceStream",
      ],
      [
        "p_snapshot_identity_kind",
        "snapshotIdentityKind",
      ],
      [
        "p_snapshot_identity_value",
        "snapshotIdentityValue",
      ],
      [
        "p_provider_source_updated_at",
        "providerSourceUpdatedAt",
      ],
      [
        "p_retrieval_id",
        "retrievalId",
      ],
      [
        "p_response_originated_at",
        "responseOriginatedAt",
      ],
      [
        "p_received_at",
        "receivedAt",
      ],
      [
        "p_provider_request_id",
        "providerRequestId",
      ],
    ];

    for (
      const [
        rpcField,
        inputField,
      ] of mappings
    ) {
      assert.match(
        source,
        new RegExp(
          `${rpcField}:\\s*[\\r\\n\\s]*input\\.${inputField}`
        )
      );
    }

    assert.match(
      source,
      /p_assertions:\s*[\r\n\s]*input\.assertions\.map/
    );
  }
);

test(
  "maps assertion provenance fields without inventing provider semantics",
  () => {
    for (
      const field of [
        "providerMessageId",
        "payloadSchemaVersion",
        "eventObservedAt",
        "providerObservationId",
        "normalizedPayload",
      ]
    ) {
      assert.match(
        source,
        new RegExp(
          `${field}:\\s*[\\r\\n\\s]*assertion\\.${field}`
        )
      );
    }
  }
);

test(
  "retrieval identity remains caller owned and is never generated by the wrapper",
  () => {
    assert.match(
      source,
      /p_retrieval_id:\s*[\r\n\s]*input\.retrievalId/
    );

    assert.match(
      source,
      /retrievalId !== expectedRetrievalId/
    );

    assert.doesNotMatch(
      source,
      /randomUUID|crypto\.randomUUID|from\s+["']uuid["']|require\s*\(\s*["']uuid["']\s*\)/
    );
  }
);

test(
  "wrapper cannot bypass the atomic RPC with direct persistence",
  () => {
    for (
      const forbidden of [
        /\.from\s*\(/,
        /\.insert\s*\(/,
        /\.update\s*\(/,
        /\.delete\s*\(/,
        /\.upsert\s*\(/,
      ]
    ) {
      assert.doesNotMatch(
        source,
        forbidden
      );
    }
  }
);

test(
  "wrapper contains no HTTP or provider-specific metadata behavior",
  () => {
    assert.doesNotMatch(
      source,
      /\bfetch\s*\(/
    );

    assert.doesNotMatch(
      source,
      /\b(?:tomtom|here)\b/i
    );

    assert.doesNotMatch(
      source,
      /TrafficModelID|Tracking-ID|lastReportTime|sourceUpdated|entryTime|startTime/
    );
  }
);

test(
  "wrapper contains no HSPP mutation or assessment behavior",
  () => {
    assert.doesNotMatch(
      source,
      /hspp_evidence|persistHspp|assessHspp/i
    );
  }
);

test(
  "RPC failure propagates fail closed",
  () => {
    assert.match(
      source,
      /if\s*\(\s*error\s*\)/
    );

    assert.match(
      source,
      /throw new Error\([\s\S]*Atomic provider snapshot persistence RPC failed/
    );
  }
);

test(
  "wrapper validates the exact one-row RPC result shape",
  () => {
    assert.match(
      source,
      /!Array\.isArray\(data\)/
    );

    assert.match(
      source,
      /data\.length !== 1/
    );

    assert.match(
      source,
      /persisted_snapshot_id/
    );

    assert.match(
      source,
      /persisted_retrieval_id/
    );

    assert.match(
      source,
      /persisted_assertion_count/
    );

    assert.match(
      source,
      /Number\.isInteger\(assertionCount\)/
    );
  }
);

test(
  "wrapper stays isolated from provider ingestion and mutable Route Safety",
  () => {
    assert.doesNotMatch(
      source,
      /importTomTomIncidents|importHereIncidents/
    );

    assert.doesNotMatch(
      source,
      /route_safety_alerts/
    );

    assert.doesNotMatch(
      source,
      /insertNewProviderAlerts/
    );
  }
);